name: Testing

on:
  push:
    branches:
      - develop

jobs:
  testing:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    strategy:
      max-parallel: 1
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: npm-${{ hashFiles('package.json') }}-${{matrix.node-version}}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install, build and test
      run: |
        npm install
        npm run build
        npm run test
